[package]
name = "hello-graph"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
juniper = "0.15"
juniper_warp = "0.7"
tokio = { version = "1.21", features = ["full"] }
warp = "0.3"
